[[aws_lc]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3586072ab23ba75ba1cfe5565343dd33cca96f9c"
libc = "glibc"
os = "linux"

    [[aws_lc.download]]
    sha256 = "0ad3d29f74b2694b94e41f9d609c760443855ae030992f5bc31da99d5922708f"
    url = "https://github.com/JuliaBinaryWrappers/aws_lc_jll.jl/releases/download/aws_lc-v1.65.0+0/aws_lc.v1.65.0.aarch64-linux-gnu-cxx11.tar.gz"
[[aws_lc]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1fb2c1b4350e60e73c63281540ead5767cd64cf9"
libc = "musl"
os = "linux"

    [[aws_lc.download]]
    sha256 = "2641ec7d94b97ee6e11445a1b480585171561e06be66d6a77221e8ba90ad0642"
    url = "https://github.com/JuliaBinaryWrappers/aws_lc_jll.jl/releases/download/aws_lc-v1.65.0+0/aws_lc.v1.65.0.aarch64-linux-musl-cxx11.tar.gz"
[[aws_lc]]
arch = "aarch64"
git-tree-sha1 = "2d2d707e0f70198db1c8eed534bc09edf9e8894e"
os = "freebsd"

    [[aws_lc.download]]
    sha256 = "78f241daece1ef022aad72163dfb1359f1442b5867bd20914531f819e0e51580"
    url = "https://github.com/JuliaBinaryWrappers/aws_lc_jll.jl/releases/download/aws_lc-v1.65.0+0/aws_lc.v1.65.0.aarch64-unknown-freebsd.tar.gz"
[[aws_lc]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "392a86f35244071f22835638f623bd9aded01fff"
libc = "glibc"
os = "linux"

    [[aws_lc.download]]
    sha256 = "38bed1f65172041921ad31a7ba8bbd365ac457e0bdee3e168498133e2682c64a"
    url = "https://github.com/JuliaBinaryWrappers/aws_lc_jll.jl/releases/download/aws_lc-v1.65.0+0/aws_lc.v1.65.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[aws_lc]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5a3702ea78f5ede80a342d84892d411d1a1a1bfc"
libc = "musl"
os = "linux"

    [[aws_lc.download]]
    sha256 = "88151fde880bcae4626e392e37940e58e75d7cc1c9965eb7e62c0a97d129c18a"
    url = "https://github.com/JuliaBinaryWrappers/aws_lc_jll.jl/releases/download/aws_lc-v1.65.0+0/aws_lc.v1.65.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[aws_lc]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9c0f05649e60d12ff4c61b5d51ca20e8a1988617"
libc = "glibc"
os = "linux"

    [[aws_lc.download]]
    sha256 = "fbc9dfbad75f61ab4ba69b9a33e20ecbf22b4b584288f4f79736d444e76a91df"
    url = "https://github.com/JuliaBinaryWrappers/aws_lc_jll.jl/releases/download/aws_lc-v1.65.0+0/aws_lc.v1.65.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[aws_lc]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "35cd40adc27053f6ecf7f223a15dd28c1b63c202"
libc = "musl"
os = "linux"

    [[aws_lc.download]]
    sha256 = "3627b10fdfb5ae9873afc6ac92869ba0efcf60ae2c94268561fc8e1dd8ba382b"
    url = "https://github.com/JuliaBinaryWrappers/aws_lc_jll.jl/releases/download/aws_lc-v1.65.0+0/aws_lc.v1.65.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[aws_lc]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7f7f52dfb783e13f75d3b8980447f037cb2113df"
libc = "glibc"
os = "linux"

    [[aws_lc.download]]
    sha256 = "010c75b5a23485f38bc0065a3d3a2c1e55d743404c304cf4b563df1814c90528"
    url = "https://github.com/JuliaBinaryWrappers/aws_lc_jll.jl/releases/download/aws_lc-v1.65.0+0/aws_lc.v1.65.0.i686-linux-gnu-cxx11.tar.gz"
[[aws_lc]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9bec532edb1b8c31ab3bf1dc6ca82bb97243e3a2"
libc = "musl"
os = "linux"

    [[aws_lc.download]]
    sha256 = "99c583307015ec61ed10f82d492139ead8776556d6ef5a029f46cf231c60ed6d"
    url = "https://github.com/JuliaBinaryWrappers/aws_lc_jll.jl/releases/download/aws_lc-v1.65.0+0/aws_lc.v1.65.0.i686-linux-musl-cxx11.tar.gz"
[[aws_lc]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "56ba81288becc4bf2820d3251d6420ac965673ee"
libc = "glibc"
os = "linux"

    [[aws_lc.download]]
    sha256 = "d5a76f34402bdd4b80debabd4e71cba955cc3736d3cbdeac8434555c99b624ed"
    url = "https://github.com/JuliaBinaryWrappers/aws_lc_jll.jl/releases/download/aws_lc-v1.65.0+0/aws_lc.v1.65.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[aws_lc]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ca953b3e7f8e337e375cfefac4e97463fd9bff89"
libc = "glibc"
os = "linux"

    [[aws_lc.download]]
    sha256 = "93fabe269f5c68dff9bfb4684dae527f20cacf6bbeb63de225dffd1cf7d04efd"
    url = "https://github.com/JuliaBinaryWrappers/aws_lc_jll.jl/releases/download/aws_lc-v1.65.0+0/aws_lc.v1.65.0.riscv64-linux-gnu-cxx11.tar.gz"
[[aws_lc]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2a8a0f992d960aea36576cd98469dee95dd9bf1a"
libc = "glibc"
os = "linux"

    [[aws_lc.download]]
    sha256 = "f198273733133af1fdec52f0222ba4e38955836fc2775fef383038488bb6787e"
    url = "https://github.com/JuliaBinaryWrappers/aws_lc_jll.jl/releases/download/aws_lc-v1.65.0+0/aws_lc.v1.65.0.x86_64-linux-gnu-cxx11.tar.gz"
[[aws_lc]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0729d094e6f53354ad3a4d9fad5e780171671d2c"
libc = "musl"
os = "linux"

    [[aws_lc.download]]
    sha256 = "ca599546627c5ec1a759f891cd3bcac4206899a223b1ee67dc6ab170d96f4c87"
    url = "https://github.com/JuliaBinaryWrappers/aws_lc_jll.jl/releases/download/aws_lc-v1.65.0+0/aws_lc.v1.65.0.x86_64-linux-musl-cxx11.tar.gz"
[[aws_lc]]
arch = "x86_64"
git-tree-sha1 = "7e98a16c7be5fecebddc1cae06678263102d1549"
os = "freebsd"

    [[aws_lc.download]]
    sha256 = "1e5e839b040246664e80f31afcb6b4492ad845fc28df45439ac1ed2574a2cbbc"
    url = "https://github.com/JuliaBinaryWrappers/aws_lc_jll.jl/releases/download/aws_lc-v1.65.0+0/aws_lc.v1.65.0.x86_64-unknown-freebsd.tar.gz"
