[[aws_lc]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "00f1bd163b9c11894bc2bb9f58793bec7f783c26"
libc = "glibc"
os = "linux"

    [[aws_lc.download]]
    sha256 = "341c13023cd221c3ba5a6f2335f4e681f71c3b9c68d97b6722b587688be482d7"
    url = "https://github.com/JuliaBinaryWrappers/aws_lc_jll.jl/releases/download/aws_lc-v1.66.0+0/aws_lc.v1.66.0.aarch64-linux-gnu-cxx11.tar.gz"
[[aws_lc]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "69762d8626b1137a822865de0a4571f17c9c92d9"
libc = "musl"
os = "linux"

    [[aws_lc.download]]
    sha256 = "cb6de61d427c59696ad04d68d7f7025a588f5589f7b43bace0f918dc0edf2b9b"
    url = "https://github.com/JuliaBinaryWrappers/aws_lc_jll.jl/releases/download/aws_lc-v1.66.0+0/aws_lc.v1.66.0.aarch64-linux-musl-cxx11.tar.gz"
[[aws_lc]]
arch = "aarch64"
git-tree-sha1 = "9d708e1e681b5eea1bc3ca4a07644acc7e9b8c03"
os = "freebsd"

    [[aws_lc.download]]
    sha256 = "5392bdeeea86cecd853a5d0f79d4535366792f883d52ebf316007c2a6ff5929b"
    url = "https://github.com/JuliaBinaryWrappers/aws_lc_jll.jl/releases/download/aws_lc-v1.66.0+0/aws_lc.v1.66.0.aarch64-unknown-freebsd.tar.gz"
[[aws_lc]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "484fbb148a50bcc1a17241f2c63a81c60f479f96"
libc = "glibc"
os = "linux"

    [[aws_lc.download]]
    sha256 = "63d10b2e209234f92ae47b88b8cedabcdce4622f53d111bc1ea4ed6d9078121b"
    url = "https://github.com/JuliaBinaryWrappers/aws_lc_jll.jl/releases/download/aws_lc-v1.66.0+0/aws_lc.v1.66.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[aws_lc]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f3ad43e0e69921c9c8604237fa74438e0a365dec"
libc = "musl"
os = "linux"

    [[aws_lc.download]]
    sha256 = "327a2a503cb34d14fc900311ee405901bc4704765bab50ac29dc22ce8980dcc4"
    url = "https://github.com/JuliaBinaryWrappers/aws_lc_jll.jl/releases/download/aws_lc-v1.66.0+0/aws_lc.v1.66.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[aws_lc]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b0cfb1213992670ceeea766ad4093d847bd951c4"
libc = "glibc"
os = "linux"

    [[aws_lc.download]]
    sha256 = "33584f25318678dddffaefafbb8d8fd5aaa3397867c531d787a8d87f7abf675a"
    url = "https://github.com/JuliaBinaryWrappers/aws_lc_jll.jl/releases/download/aws_lc-v1.66.0+0/aws_lc.v1.66.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[aws_lc]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0445440e3ee2671d7fe41acc239b302ab4998bba"
libc = "musl"
os = "linux"

    [[aws_lc.download]]
    sha256 = "99e1a4c6e521a077dcbbc505ecd7325752d9e6665decb90e840b67933ef7892d"
    url = "https://github.com/JuliaBinaryWrappers/aws_lc_jll.jl/releases/download/aws_lc-v1.66.0+0/aws_lc.v1.66.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[aws_lc]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3918ba0bf0611b501ed63976a33f2fe9bcb14dff"
libc = "glibc"
os = "linux"

    [[aws_lc.download]]
    sha256 = "0a39b18f91d8610edc653552b5f2e512a161baf297f5597dc318afbc7ae42d93"
    url = "https://github.com/JuliaBinaryWrappers/aws_lc_jll.jl/releases/download/aws_lc-v1.66.0+0/aws_lc.v1.66.0.i686-linux-gnu-cxx11.tar.gz"
[[aws_lc]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0959b3a5acd4ab014a25c7483a6af7ed5e5e24c4"
libc = "musl"
os = "linux"

    [[aws_lc.download]]
    sha256 = "c4c960c08c5c680e53552ba8ebacdbe428a9e4b92d19ff9c5b88837312494e0a"
    url = "https://github.com/JuliaBinaryWrappers/aws_lc_jll.jl/releases/download/aws_lc-v1.66.0+0/aws_lc.v1.66.0.i686-linux-musl-cxx11.tar.gz"
[[aws_lc]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "120b9792a4bbd202ebee0e955483d3a97c1f0862"
libc = "glibc"
os = "linux"

    [[aws_lc.download]]
    sha256 = "29b45106914edddc4c10bbcdc886797cb5e6a2a9da9c982865daf1183743a764"
    url = "https://github.com/JuliaBinaryWrappers/aws_lc_jll.jl/releases/download/aws_lc-v1.66.0+0/aws_lc.v1.66.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[aws_lc]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7c19aaa49b04225512455d45d4f3067b6086b16f"
libc = "glibc"
os = "linux"

    [[aws_lc.download]]
    sha256 = "3756c38e5802c9b15f7a4c79504b1db044215a6826a74ce96fd4bd21da0a453b"
    url = "https://github.com/JuliaBinaryWrappers/aws_lc_jll.jl/releases/download/aws_lc-v1.66.0+0/aws_lc.v1.66.0.riscv64-linux-gnu-cxx11.tar.gz"
[[aws_lc]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8a708c6707de01c5ad01e9d8cb738a0b23008ad3"
libc = "glibc"
os = "linux"

    [[aws_lc.download]]
    sha256 = "5b6d8929cc19713b69de52694d8a61c410c7e0e915c175f92033efac1fb35d68"
    url = "https://github.com/JuliaBinaryWrappers/aws_lc_jll.jl/releases/download/aws_lc-v1.66.0+0/aws_lc.v1.66.0.x86_64-linux-gnu-cxx11.tar.gz"
[[aws_lc]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bcdd534457be6c0ea93214173468a008f72b7689"
libc = "musl"
os = "linux"

    [[aws_lc.download]]
    sha256 = "eb5a6afe7b9c548a54e7d581e200437bb79aa99490c1c34801dee8136d281ba1"
    url = "https://github.com/JuliaBinaryWrappers/aws_lc_jll.jl/releases/download/aws_lc-v1.66.0+0/aws_lc.v1.66.0.x86_64-linux-musl-cxx11.tar.gz"
[[aws_lc]]
arch = "x86_64"
git-tree-sha1 = "fedde50567c61ca0a801374a37c50616bc12167e"
os = "freebsd"

    [[aws_lc.download]]
    sha256 = "eba7dfc3cdce4a9d27c8c3e256d0900ae90713ce67994212501cb47731dd563f"
    url = "https://github.com/JuliaBinaryWrappers/aws_lc_jll.jl/releases/download/aws_lc-v1.66.0+0/aws_lc.v1.66.0.x86_64-unknown-freebsd.tar.gz"
