[[aws_lc]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "be6b28f1d1eac5e6118437e91761b72ad5cbf462"
libc = "glibc"
os = "linux"

    [[aws_lc.download]]
    sha256 = "69d6d080a2c9a6d923e70a49bbff87866e1db4f7288864d3288d707a6e8ab33a"
    url = "https://github.com/JuliaBinaryWrappers/aws_lc_jll.jl/releases/download/aws_lc-v1.64.0+0/aws_lc.v1.64.0.aarch64-linux-gnu-cxx11.tar.gz"
[[aws_lc]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f4d084b6cf123b2b90ec52cb0bc0e5b297c6e6a6"
libc = "musl"
os = "linux"

    [[aws_lc.download]]
    sha256 = "75f7ae98aa7ae9db792cff86d3d17886458cef5aaafa50218c129b9975f54a4f"
    url = "https://github.com/JuliaBinaryWrappers/aws_lc_jll.jl/releases/download/aws_lc-v1.64.0+0/aws_lc.v1.64.0.aarch64-linux-musl-cxx11.tar.gz"
[[aws_lc]]
arch = "aarch64"
git-tree-sha1 = "9f56983cf32bb62fefe37e8c97a412c1d55f19e1"
os = "freebsd"

    [[aws_lc.download]]
    sha256 = "55fc740bb1a5ac23d61312caaf58be2b43ad18146d38267c05cbc22239de8578"
    url = "https://github.com/JuliaBinaryWrappers/aws_lc_jll.jl/releases/download/aws_lc-v1.64.0+0/aws_lc.v1.64.0.aarch64-unknown-freebsd.tar.gz"
[[aws_lc]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0d67b97a26de0c7176e22cc4fcb4793b78fba6e3"
libc = "glibc"
os = "linux"

    [[aws_lc.download]]
    sha256 = "d6e2ee5ee806ef0f7c6857b4eac2f08df994c4ac2fa3f1e6e214186f53992e65"
    url = "https://github.com/JuliaBinaryWrappers/aws_lc_jll.jl/releases/download/aws_lc-v1.64.0+0/aws_lc.v1.64.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[aws_lc]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a741db4a2401f585e261742514e5310f7bafe149"
libc = "musl"
os = "linux"

    [[aws_lc.download]]
    sha256 = "9ddbcffcdba724509ddfc8d4f11a8d378a95956b2582d5a5eca39a26595444e0"
    url = "https://github.com/JuliaBinaryWrappers/aws_lc_jll.jl/releases/download/aws_lc-v1.64.0+0/aws_lc.v1.64.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[aws_lc]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "df6251e27a351c6b2946012af15723961083180d"
libc = "glibc"
os = "linux"

    [[aws_lc.download]]
    sha256 = "4b7e75abe6deda16b293063b40aef6321378513ba9195daefbff83cc260c5a39"
    url = "https://github.com/JuliaBinaryWrappers/aws_lc_jll.jl/releases/download/aws_lc-v1.64.0+0/aws_lc.v1.64.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[aws_lc]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "22f1277b8fcb21a5ae7bb76f42a0bad4d8fa71e3"
libc = "musl"
os = "linux"

    [[aws_lc.download]]
    sha256 = "d929fe616f401702c4c217ba5acf851ac95de9d03c1c3a0faeb9bae79438aee6"
    url = "https://github.com/JuliaBinaryWrappers/aws_lc_jll.jl/releases/download/aws_lc-v1.64.0+0/aws_lc.v1.64.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[aws_lc]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a10e42fbe420c3e74fcd76b9c23801a85faae02a"
libc = "glibc"
os = "linux"

    [[aws_lc.download]]
    sha256 = "452eb98d1509f3f58cde51fc5399c2856d312fb6d2b87265a30177d17b22696d"
    url = "https://github.com/JuliaBinaryWrappers/aws_lc_jll.jl/releases/download/aws_lc-v1.64.0+0/aws_lc.v1.64.0.i686-linux-gnu-cxx11.tar.gz"
[[aws_lc]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8acc4a25759058f3c36f87df40047d48b285e93d"
libc = "musl"
os = "linux"

    [[aws_lc.download]]
    sha256 = "a9e5e83a8fdbddc0140fa59832ea41ecb21e1a7c3969e1e9efdd7cabf5ef4563"
    url = "https://github.com/JuliaBinaryWrappers/aws_lc_jll.jl/releases/download/aws_lc-v1.64.0+0/aws_lc.v1.64.0.i686-linux-musl-cxx11.tar.gz"
[[aws_lc]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "55f7a425458f40f64813f975260e7062b0f45a10"
libc = "glibc"
os = "linux"

    [[aws_lc.download]]
    sha256 = "ec4311b9e0c25b9b5dab5bc6f7c4326557009b3d334b4ae1576f4ca30231080b"
    url = "https://github.com/JuliaBinaryWrappers/aws_lc_jll.jl/releases/download/aws_lc-v1.64.0+0/aws_lc.v1.64.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[aws_lc]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "624b09018598bb092842a7831102d50532afb2ba"
libc = "glibc"
os = "linux"

    [[aws_lc.download]]
    sha256 = "339663b33f5aec161e42f3c153c2845f05e6a541e60923ea15e147edf655c51c"
    url = "https://github.com/JuliaBinaryWrappers/aws_lc_jll.jl/releases/download/aws_lc-v1.64.0+0/aws_lc.v1.64.0.riscv64-linux-gnu-cxx11.tar.gz"
[[aws_lc]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "45556b227bbe498c83722760918663f0ca3aec9f"
libc = "glibc"
os = "linux"

    [[aws_lc.download]]
    sha256 = "0ec55c83202e63f6783bc26c1ba9c2064e02ee490c2583492bd68324f829c194"
    url = "https://github.com/JuliaBinaryWrappers/aws_lc_jll.jl/releases/download/aws_lc-v1.64.0+0/aws_lc.v1.64.0.x86_64-linux-gnu-cxx11.tar.gz"
[[aws_lc]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7709cb8ce800e1e7242e7b8876c437ac57a65f83"
libc = "musl"
os = "linux"

    [[aws_lc.download]]
    sha256 = "4ac0e2af96af9598b59caf012eea1eccc6e94dc561a5f5bce791f51b9b457f5e"
    url = "https://github.com/JuliaBinaryWrappers/aws_lc_jll.jl/releases/download/aws_lc-v1.64.0+0/aws_lc.v1.64.0.x86_64-linux-musl-cxx11.tar.gz"
[[aws_lc]]
arch = "x86_64"
git-tree-sha1 = "851a46f58b87ff6fa27176c4ccc015e84b2ccd72"
os = "freebsd"

    [[aws_lc.download]]
    sha256 = "44fd5a141740a0e37300206c4ba52836ba8b19d5f68a8751cc46aa3b8da46a23"
    url = "https://github.com/JuliaBinaryWrappers/aws_lc_jll.jl/releases/download/aws_lc-v1.64.0+0/aws_lc.v1.64.0.x86_64-unknown-freebsd.tar.gz"
