[[aws_lc]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4b3d30c9f54368ddeaf337b1d9256998cd17a082"
libc = "glibc"
os = "linux"

    [[aws_lc.download]]
    sha256 = "02035386d5c87ad52ec29fb06d2fcc9492096663e56758cc0867a0ce32439b20"
    url = "https://github.com/JuliaBinaryWrappers/aws_lc_jll.jl/releases/download/aws_lc-v1.65.1+0/aws_lc.v1.65.1.aarch64-linux-gnu-cxx11.tar.gz"
[[aws_lc]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b8292487ef40d2e3c3825b7c7ee8294d21adac76"
libc = "musl"
os = "linux"

    [[aws_lc.download]]
    sha256 = "88ca1b0286e1e2451fedf0ea20c93286e971bdf39c13f8897e4d334a6e3233f7"
    url = "https://github.com/JuliaBinaryWrappers/aws_lc_jll.jl/releases/download/aws_lc-v1.65.1+0/aws_lc.v1.65.1.aarch64-linux-musl-cxx11.tar.gz"
[[aws_lc]]
arch = "aarch64"
git-tree-sha1 = "92697ac1b4164c70cfd7cd55d6d83312a226ae4b"
os = "freebsd"

    [[aws_lc.download]]
    sha256 = "064d884651fc505f86f1375975053be74a2a61fe45cc99f6b76a7c77d964a2ed"
    url = "https://github.com/JuliaBinaryWrappers/aws_lc_jll.jl/releases/download/aws_lc-v1.65.1+0/aws_lc.v1.65.1.aarch64-unknown-freebsd.tar.gz"
[[aws_lc]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d3fe6568e7357c6f9d1e0ec99a56be5715f13dde"
libc = "glibc"
os = "linux"

    [[aws_lc.download]]
    sha256 = "0def07161ee62230040f356cde2bf595159488c6252349d209546e7c9b17f129"
    url = "https://github.com/JuliaBinaryWrappers/aws_lc_jll.jl/releases/download/aws_lc-v1.65.1+0/aws_lc.v1.65.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[aws_lc]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3404febfe45e871e230428ee87b6633496924ade"
libc = "musl"
os = "linux"

    [[aws_lc.download]]
    sha256 = "08aa8312320f7d744632d4d05b23a5b250489a1ca5ce3e2bb1507c148728f8da"
    url = "https://github.com/JuliaBinaryWrappers/aws_lc_jll.jl/releases/download/aws_lc-v1.65.1+0/aws_lc.v1.65.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[aws_lc]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c5677d4e47ee2d8ee63b1caec0ef24e062f646d5"
libc = "glibc"
os = "linux"

    [[aws_lc.download]]
    sha256 = "7d8c0f2c606eb9f998003427a9318d70d6f6d76cbcd6dde3118bb3664ea76241"
    url = "https://github.com/JuliaBinaryWrappers/aws_lc_jll.jl/releases/download/aws_lc-v1.65.1+0/aws_lc.v1.65.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[aws_lc]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b02a2d5672d7d3bd6a664583001b8bdccc08955c"
libc = "musl"
os = "linux"

    [[aws_lc.download]]
    sha256 = "fb80030f78df63e3c748b332abbeed8d66b17689783e7fd7aaf5ec0f031cae51"
    url = "https://github.com/JuliaBinaryWrappers/aws_lc_jll.jl/releases/download/aws_lc-v1.65.1+0/aws_lc.v1.65.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[aws_lc]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7006051f39f464af6784dff8518de623fa06f8de"
libc = "glibc"
os = "linux"

    [[aws_lc.download]]
    sha256 = "ab7b67f9509cc0e5a8148387575073f06a5ce7f2cf63fb62898b8a94c0111fd8"
    url = "https://github.com/JuliaBinaryWrappers/aws_lc_jll.jl/releases/download/aws_lc-v1.65.1+0/aws_lc.v1.65.1.i686-linux-gnu-cxx11.tar.gz"
[[aws_lc]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f8382863ea1bef4c8a617cd2c61afae553377c3b"
libc = "musl"
os = "linux"

    [[aws_lc.download]]
    sha256 = "8ad06c148cb877149e12e4759ee639efd262678e5cdb9f00ac2c9ccd34f683f1"
    url = "https://github.com/JuliaBinaryWrappers/aws_lc_jll.jl/releases/download/aws_lc-v1.65.1+0/aws_lc.v1.65.1.i686-linux-musl-cxx11.tar.gz"
[[aws_lc]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c7aa349b4d3c879a5393d1eb1855eb9c7e062ccb"
libc = "glibc"
os = "linux"

    [[aws_lc.download]]
    sha256 = "be17eb551e1d327b08eda63eb69d7f1edfda1acb7dc74b24ac7c287cf4a8e3f4"
    url = "https://github.com/JuliaBinaryWrappers/aws_lc_jll.jl/releases/download/aws_lc-v1.65.1+0/aws_lc.v1.65.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[aws_lc]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "41b5d4e1d609268e06bcf8d8e75c811c74403960"
libc = "glibc"
os = "linux"

    [[aws_lc.download]]
    sha256 = "95a9824b490e6ae793e95bda47c02858c1eb3f213c2fe8146ca552f4ea81375b"
    url = "https://github.com/JuliaBinaryWrappers/aws_lc_jll.jl/releases/download/aws_lc-v1.65.1+0/aws_lc.v1.65.1.riscv64-linux-gnu-cxx11.tar.gz"
[[aws_lc]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d0104037b3de36c95b755a5e3afb20d18fc797ed"
libc = "glibc"
os = "linux"

    [[aws_lc.download]]
    sha256 = "c6f2d80d045a7d502d6ff55cbbf953eafcb4a25d7f350e97a68a28a34722dc28"
    url = "https://github.com/JuliaBinaryWrappers/aws_lc_jll.jl/releases/download/aws_lc-v1.65.1+0/aws_lc.v1.65.1.x86_64-linux-gnu-cxx11.tar.gz"
[[aws_lc]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d28577d754200cb61a73d7142e0535c06b81f867"
libc = "musl"
os = "linux"

    [[aws_lc.download]]
    sha256 = "cdcfe936bb66c323107247107784319afe6e34bc01c76ffebaef7816bb97c90c"
    url = "https://github.com/JuliaBinaryWrappers/aws_lc_jll.jl/releases/download/aws_lc-v1.65.1+0/aws_lc.v1.65.1.x86_64-linux-musl-cxx11.tar.gz"
[[aws_lc]]
arch = "x86_64"
git-tree-sha1 = "4ae954defdaec26e1cf970d7bb9b47fdd22b7342"
os = "freebsd"

    [[aws_lc.download]]
    sha256 = "a4e25f03e610dcf20838c4e30a4f77403160e4d1973295afb01e59c4affc2e62"
    url = "https://github.com/JuliaBinaryWrappers/aws_lc_jll.jl/releases/download/aws_lc-v1.65.1+0/aws_lc.v1.65.1.x86_64-unknown-freebsd.tar.gz"
