[[aws_lc]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a667f57778cef37650b9f35cfb9bc2df3c81a6c7"
libc = "glibc"
os = "linux"

    [[aws_lc.download]]
    sha256 = "cafd2be453588a544ef94c6a7db44c6d6674efae02f6d86047939b0af550c6db"
    url = "https://github.com/JuliaBinaryWrappers/aws_lc_jll.jl/releases/download/aws_lc-v1.66.1+0/aws_lc.v1.66.1.aarch64-linux-gnu-cxx11.tar.gz"
[[aws_lc]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "96f8c8563559cd686f55a17f30c6e426b7e35747"
libc = "musl"
os = "linux"

    [[aws_lc.download]]
    sha256 = "d7d8290d194db71fad190530caeb1a59947c0263ed6bfbd1477e6b4f4dc51470"
    url = "https://github.com/JuliaBinaryWrappers/aws_lc_jll.jl/releases/download/aws_lc-v1.66.1+0/aws_lc.v1.66.1.aarch64-linux-musl-cxx11.tar.gz"
[[aws_lc]]
arch = "aarch64"
git-tree-sha1 = "c3b7c574fbf198b6b9121160a9bf3ebdc73d4f0e"
os = "freebsd"

    [[aws_lc.download]]
    sha256 = "54ecab3b91e11e759ca2f22be4854269fdda2eb90dcc0c4910fafaae108741d8"
    url = "https://github.com/JuliaBinaryWrappers/aws_lc_jll.jl/releases/download/aws_lc-v1.66.1+0/aws_lc.v1.66.1.aarch64-unknown-freebsd.tar.gz"
[[aws_lc]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "afbe242132e936f1c943fa386440e540c7e78268"
libc = "glibc"
os = "linux"

    [[aws_lc.download]]
    sha256 = "9d7207cc4c21bede84e34a6a5c82bed42711c8a2f0d0b893a70e2873ed027507"
    url = "https://github.com/JuliaBinaryWrappers/aws_lc_jll.jl/releases/download/aws_lc-v1.66.1+0/aws_lc.v1.66.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[aws_lc]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "86eb9188b9a4c3c4c409154ce45eb13fbfc4e62d"
libc = "musl"
os = "linux"

    [[aws_lc.download]]
    sha256 = "b404b9cf807d5cdbebc0234b4054e75f8c6616e404952927201a448e53da2e15"
    url = "https://github.com/JuliaBinaryWrappers/aws_lc_jll.jl/releases/download/aws_lc-v1.66.1+0/aws_lc.v1.66.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[aws_lc]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cbd7efc4cd921614b569048b75da1f2c0a8205bd"
libc = "glibc"
os = "linux"

    [[aws_lc.download]]
    sha256 = "8a76956983f73aae4d1ed6d3d777b01cd7850b993ceee262a4f9e212ea7158d4"
    url = "https://github.com/JuliaBinaryWrappers/aws_lc_jll.jl/releases/download/aws_lc-v1.66.1+0/aws_lc.v1.66.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[aws_lc]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d5b85cfb6685261b50c7d663fb6ee095d33ef597"
libc = "musl"
os = "linux"

    [[aws_lc.download]]
    sha256 = "4a8deefccd5c82647d729fb978b59d584f505171c93b112cbd91174fe97f64a8"
    url = "https://github.com/JuliaBinaryWrappers/aws_lc_jll.jl/releases/download/aws_lc-v1.66.1+0/aws_lc.v1.66.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[aws_lc]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "79a43ccb81c10e50549e4ada5abba00003ba713e"
libc = "glibc"
os = "linux"

    [[aws_lc.download]]
    sha256 = "6ddfe1f6a3358bfe5e26539886cfbb40ae4459d736326dfc7b9c521c132142da"
    url = "https://github.com/JuliaBinaryWrappers/aws_lc_jll.jl/releases/download/aws_lc-v1.66.1+0/aws_lc.v1.66.1.i686-linux-gnu-cxx11.tar.gz"
[[aws_lc]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "13e3be7ed4dd7ab69e5d481bf5d844d7cd5b5227"
libc = "musl"
os = "linux"

    [[aws_lc.download]]
    sha256 = "f922f9140aee309fe827f9bc785d1027f4e18674b0e3a874dd4c5ec8f50cbb36"
    url = "https://github.com/JuliaBinaryWrappers/aws_lc_jll.jl/releases/download/aws_lc-v1.66.1+0/aws_lc.v1.66.1.i686-linux-musl-cxx11.tar.gz"
[[aws_lc]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d24027a34c6f91a1986570aa99944569feb813d9"
libc = "glibc"
os = "linux"

    [[aws_lc.download]]
    sha256 = "ca4cb441d7bf08cb4890c54014839946c7a88d9c6713ae95cfaf3632da57e110"
    url = "https://github.com/JuliaBinaryWrappers/aws_lc_jll.jl/releases/download/aws_lc-v1.66.1+0/aws_lc.v1.66.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[aws_lc]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2f04cb9e5396ffa080313b9a3eaaaeef1f97d7f0"
libc = "glibc"
os = "linux"

    [[aws_lc.download]]
    sha256 = "5731bf074b31798a2c8dcbdb6593974c162975d08556ae4e321fce0aa9835638"
    url = "https://github.com/JuliaBinaryWrappers/aws_lc_jll.jl/releases/download/aws_lc-v1.66.1+0/aws_lc.v1.66.1.riscv64-linux-gnu-cxx11.tar.gz"
[[aws_lc]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "715c509bd93347b0375e7272a30f8e68f44f990f"
libc = "glibc"
os = "linux"

    [[aws_lc.download]]
    sha256 = "1acf936eb0fbbb0000c6063732585bb8b4e821942f528410fc926159e7d8ac66"
    url = "https://github.com/JuliaBinaryWrappers/aws_lc_jll.jl/releases/download/aws_lc-v1.66.1+0/aws_lc.v1.66.1.x86_64-linux-gnu-cxx11.tar.gz"
[[aws_lc]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5a0e13f42af6ffae12f8c7550ac5642fc3398c87"
libc = "musl"
os = "linux"

    [[aws_lc.download]]
    sha256 = "77560984a128432bdf67792b06a7f0b2692843a4fcb3bf4bef6dd183efce31f0"
    url = "https://github.com/JuliaBinaryWrappers/aws_lc_jll.jl/releases/download/aws_lc-v1.66.1+0/aws_lc.v1.66.1.x86_64-linux-musl-cxx11.tar.gz"
[[aws_lc]]
arch = "x86_64"
git-tree-sha1 = "f26a60f9a1054449e0b3181ecd3be70b8d24f9b0"
os = "freebsd"

    [[aws_lc.download]]
    sha256 = "6e6100083291dbd57f171addd21208a48ef09ec80941d68ce4539e2ea64ed9e7"
    url = "https://github.com/JuliaBinaryWrappers/aws_lc_jll.jl/releases/download/aws_lc-v1.66.1+0/aws_lc.v1.66.1.x86_64-unknown-freebsd.tar.gz"
